Minor fixes
seanmiddleditch/libtelnet pull request #48
Opened 2018-11-18 12:36 UTC by hefloryd

Allow LIBTELNET_STRICT on libtelnet.c. Fix some warnings resulting from this. Also allow build to complete if Doxygen is not installed.

2018-11-18 14:24 UTC, hefloryd commented
Enabled C99 to fix C++ style comments warning - perhaps it would be better to just change style to plain C comments instead?

2018-11-18 21:33 UTC, seanmiddleditch requested changes
Mostly looks good. I agree with your last comment that we should just replace the C99 comments with C89 comments instead of requiring C99 to compile, at least for now.

A completely separate PR can do a pass over the code and modernize it to C99. I wouldn't be surprised if that finds and fixes some bugs, too.

2018-11-19 12:04 UTC, hefloryd commented
Sounds good, replaced C99 commit with new commit changing comment style instead.

2018-11-20 19:11 UTC, seanmiddleditch approved these changes

2018-11-20 19:11 UTC, merged